
export const ON_SUBMIT = "ON_SUBMIT";
export const ON_CLEAR = "ON_CLEAR";

export const COINS = {
  GENERATE_COINS: "GENERATE_COINS",
  RESET_COINS: "RESET_COINS",
  REDEEM_COINS: "REDEEM_COINS",
  NEXT_PRICE: "NEXT_PRICE",
  CURRENT_PRICE: "CURRENT_PRICE",
};

export const GENERATE_USER = {
  CREATE_USER: "CREATE_USER",
  FORM_SUBMIT: "FORM_SUBMIT",
  RESET_INPUT_VALUE: "RESET_INPUT_VALUE",
  SET_ACTIVE_CLASS: "SET_ACTIVE_CLASS",
  SET_ACTIVE_SLIDE_INDEX: "SET_ACTIVE_SLIDE_INDEX",
  RESET_ACTIVE_SLIDE_INDEX: "RESET_ACTIVE_SLIDE_INDEX",
  MAX_USER: "MAX_USER",
  RESET_USER_VALUES: "RESET_USER_VALUES",
};

export const RESULT = {
  ADD_RESULT: "ADD_RESULT",
  IS_RESULT_DECLARED: "IS_RESULT_DECLARED",
  CLEAR_RESULT: "CLEAR_RESULT",
};

export const AUTOGENERATE = {
  AUTO_GENERATE_USER: "AUTO_GENERATE_USER",
};

export const ONCHNAGE = {
  SET_ONCHNAGE: "SET_ONCHNAGE",
  CLEAR_INPUT_VALUES: "CLEAR_INPUT_VALUES",
  SET_ON_CHANGE: "SET_ON_CHANGE",
};